.TH MMAILTO 8l "18 May r1.6
.SH NAME
.B mmailto
- wrapper script to invoke mutt from the 
\fBmailto:\fR URI in
.BR firefox .
.SH SYNOPSIS
\fBmmailto\fR
[[\fB-c \fI<config_file>\fR]
[\fB-d\fR]
[\fB-v \fR]] | [\fB-V\fR]]
.br
.SH AVAILABILITY
.B mmailto
is a Bourne shell script which should work equally well on all versions of UNIX,
Linux and Mac OS X.
.SH DESCRIPTION
.B mmailto
passes the parameters from the 
.B mailto: 
URI to a virtual terminal running
.BR mutt .
.SH OPTIONS
.TP 5
.B -c
Use the specified configuration file in preference to the default
\fI"/usr/local/etc/mmailto.cf"\fR.
If no configuration file is found the 
script will continue with the default MUA
.B mutt
running in "\fBterminal\fR".
.TP 5
.B -d
Set debug mode on. 
The \fB-x\fR option is set within the shell
and each command in the script is echoed to the console.
.TP 5
.B -v
Doesn't do anything at all at present and probably never will.
.TP 5
.B -V
Prints version details and terminates.
.SH FILES
.IR mmailto.cf .
.SH EXAMPLES
.IP
.LP
In 
.B firefox
select
.br
"prefences", "applications", "mailto", "Use other ...".
.LP
Type in the full path name to the script as below.
.nf
.ft CW
	/usr/local/bin/mmailto 
.ft R
.fi
.SH BUGS
The script is quite crude and has very little, if any,  error checking.
The consequences of unexpected input are untested.
.SH SEE ALSO
.IR webupd .
.SH AUTHOR
Clifford W Fulford, City Linux. Contact fulford@fulford.net or +44 (0)709 229 5385.
.SH HISTORY
