#!/bin/bash
# $Id: mmailto,v 1.6 2015/05/16 06:57:26 fulford Exp $
# $Source: /src/merlin/usr/local/etc/RCS/mmailto,v $
# $Revision: 1.6 $
# Author C W Fulford.
# Copyright 2014 (c) C W Fulford.
# Licensed for public use under the LGPL, .
# For assistance contact fulford@fulford.net 0709 229 5385
########################################################################
cmd=`basename $0`
syntax="$cmd [[-d] [-v]] | [-V]"
while [ $# -gt 0 ] ;do
	case $1 in 
		-c) config=$2;shift;;
		-d) debug=:;set -x;shift;;
		-v) verbose=0;shift;;
		-V) echo "$cmd $Revision: 1.6 $ $Date: 2015/05/16 06:57:26 $"|awk '{print $1,$3,$6}';exit;;  
		*)params="$@";shift;continue;;
	esac
done
config=${config:-"/usr/local/etc/mmailto.cf"}
. $config
$vterm "$mua" "$params"
